export const NEXT_PUBLIC_KAKAO_BASE_URI =
  process.env.NEXT_PUBLIC_KAKAO_BASE_URI;

export const NEXT_PUBLIC_KAKAO_CLIENT_ID =
  process.env.NEXT_PUBLIC_KAKAO_CLIENT_ID;

export const NEXT_PUBLIC_SCOPE = process.env.NEXT_PUBLIC_SCOPE;

export const NEXT_PUBLIC_KAKAO_REDIRECT_URI =
  process.env.NEXT_PUBLIC_KAKAO_REDIRECT_URI;
